AIRTUNES_SERVER = ENV['AIRTUNES_SERVER'] || 'tweeter.local'
JUKEBOX_MUSIC_ROOT = ENV['JUKEBOX_MUSIC'] || "#{RAILS_ROOT}/music"
JUKEBOX_MUSIC_FILES = "#{JUKEBOX_MUSIC_ROOT}/*.mp3"
TEMP_SNIPPETS_FILE = "#{RAILS_ROOT}/tmp/temp_snippet.mp3"